/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cytoscape.cyndex2.internal.ui.swing;

import org.cytoscape.cyndex2.internal.util.CxPreferences;
import org.ndexbio.model.object.network.NetworkSummary;

/**
 *
 * @author wilderkrieger
 */
public class LargeNetworkDialog extends javax.swing.JDialog {

	private final NetworkSummary networkSummary;

	/**
	 * Creates new form ViewCreationDialog
	 */
	public LargeNetworkDialog(java.awt.Frame parent, boolean modal, final NetworkSummary networkSummary) {
		super(parent, modal);
		this.networkSummary = networkSummary;
		initComponents();
	}

	private void updateHeadingAndMessage() {
		
		if (willCreateView()) {
			createViewRadioButton.setSelected(true);}
		else {
			dontCreateViewRadioButton.setSelected(true);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        preferencesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createViewRadioButton = new javax.swing.JRadioButton();
        dontCreateViewRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Network Import Confirmation");

        jLabel1.setText("<html>View creation for a network of this size requires large amounts of memory and could cause problems on less powerful computers.<br/><br/>You can manually set view creation for this import below.</html>");
        jLabel1.setMaximumSize(new java.awt.Dimension(62, 63));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        preferencesButton.setText("Preferences...");
        preferencesButton.setToolTipText("Network Import Settings");
        preferencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("You are about to import a large network.");

        viewButtonGroup.add(createViewRadioButton);
        createViewRadioButton.setText("Create View");
        createViewRadioButton.setSelected(willCreateView());

        viewButtonGroup.add(dontCreateViewRadioButton);
        dontCreateViewRadioButton.setText("Don't Create View");
        dontCreateViewRadioButton.setSelected(!willCreateView());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(createViewRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dontCreateViewRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preferencesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createViewRadioButton)
                    .addComponent(dontCreateViewRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preferencesButton)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		// TODO add your handling code here:
		setImportNetwork(true);
		setVisible(false);
	}// GEN-LAST:event_okButtonActionPerformed

	private void preferencesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_settingsButtonActionPerformed
		PreferencesDialog preferencesDialog = new PreferencesDialog(null, true);
		preferencesDialog.setLocationRelativeTo(this);
		preferencesDialog.setVisible(true);
		updateHeadingAndMessage();
	}// GEN-LAST:event_settingsButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed

		// TODO add your handling code here:
		setImportNetwork(false);
		setVisible(false);
	}// GEN-LAST:event_cancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				NetworkSummary networkSummary = new NetworkSummary();
				networkSummary.setNodeCount(1000000);
				networkSummary.setEdgeCount(1000000);

				LargeNetworkDialog dialog = new LargeNetworkDialog(new javax.swing.JFrame(), true, networkSummary);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton createViewRadioButton;
    private javax.swing.JRadioButton dontCreateViewRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    private javax.swing.JButton preferencesButton;
    private javax.swing.ButtonGroup viewButtonGroup;
    // End of variables declaration//GEN-END:variables

	private boolean willCreateView() {
		final long networkSize = networkSummary.getNodeCount() + networkSummary.getEdgeCount();

		final long viewThreshold = CxPreferences.getViewThreshold();
		final CxPreferences.CreateViewEnum createViewPreference = CxPreferences.getCreateView();

		return createViewPreference.equals(CxPreferences.CreateViewEnum.ALWAYS) || networkSize < viewThreshold;
	}

	private boolean importNetwork = false;

	private void setImportNetwork(final boolean importNetwork) {
		this.importNetwork = importNetwork;
	}

	public boolean getImportNetwork() {
		return importNetwork;
	}
	
	public boolean getCreateView() {
		return createViewRadioButton.isSelected();
	}
}
