/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cytoscape.cyndex2.internal.ui.swing;

import org.cytoscape.cyndex2.internal.CyServiceModule;
import org.cytoscape.cyndex2.internal.util.CxPreferences;
import org.cytoscape.util.swing.IconManager;
import org.ndexbio.model.object.network.NetworkSummary;

import static org.cytoscape.util.swing.IconManager.ICON_QUESTION_CIRCLE_O;

import java.awt.Dialog;

import javax.swing.JOptionPane;

/**
 *
 * @author David Otasek
 */
public class LargeNetworkDialog extends javax.swing.JDialog {

	private final NetworkSummary networkSummary;

	final int ICON_FONT_SIZE = 22;
	
	private final String CREATE_VIEW_TIP = "<html><p width=\"200px\">Choose this option to import the network and display it <u>preserving the original layout and visual styling info</u>. Your computer might crash if it's older or not powerful enough.</p></html>";
	private final String DONT_CREATE_VIEW_TIP = "<html><p width=\"200px\">Choose this option to import the network without generating a graphic rendering. The <u>original layout and visual styling info will be lost</u>. You can decide to generate a graphic rendering later if desired.</p></html>";
	
	/**
	 * Creates new form ViewCreationDialog
	 */
	public LargeNetworkDialog(Dialog parent, boolean modal, final NetworkSummary networkSummary) {
		super(parent, modal);
		this.networkSummary = networkSummary;
		initComponents();
	}

	private void validateOK() {
		okButton.setEnabled(createViewRadioButton.isSelected() || dontCreateViewRadioButton.isSelected());
	}
	
	private void updateHeadingAndMessage() {
		
		if (willCreateView()) {
			createViewRadioButton.setSelected(true);}
		else {
			dontCreateViewRadioButton.setSelected(true);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        createViewRadioButton = new javax.swing.JRadioButton();
        dontCreateViewRadioButton = new javax.swing.JRadioButton();
        createViewInfo = new javax.swing.JLabel();
        dontCreateViewInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Network Import Confirmation");

        jLabel1.setText("<html>You are about to import a large network. Creating a view for a network of this size requires large amounts of memory and could cause problems on less powerful computers. Please choose one of the following options.</html>");
        jLabel1.setMaximumSize(new java.awt.Dimension(62, 63));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        viewButtonGroup.add(createViewRadioButton);
        createViewRadioButton.setText("<html><b>Create View</b> (Resource Intensive, layout and visual properties are preserved)</html>");
        createViewRadioButton.setToolTipText(CREATE_VIEW_TIP);
        createViewRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                createViewRadioButtonStateChanged(evt);
            }
        });

        viewButtonGroup.add(dontCreateViewRadioButton);
        dontCreateViewRadioButton.setText("<html><b>Don't Create View</b> (Faster, layout and visual properties are discarded) </html>");
        dontCreateViewRadioButton.setToolTipText(DONT_CREATE_VIEW_TIP);
        dontCreateViewRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dontCreateViewRadioButtonStateChanged(evt);
            }
        });
        dontCreateViewRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontCreateViewRadioButtonActionPerformed(evt);
            }
        });

        createViewInfo.setFont(CyServiceModule.getService(IconManager.class).getIconFont(ICON_FONT_SIZE * 4 / 5));
        createViewInfo.setText(ICON_QUESTION_CIRCLE_O);
        createViewInfo.setToolTipText(CREATE_VIEW_TIP);
        createViewInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createViewInfo.setMaximumSize(new java.awt.Dimension(32, 32));
        createViewInfo.setMinimumSize(new java.awt.Dimension(24, 24));
        createViewInfo.setPreferredSize(new java.awt.Dimension(24, 24));
        createViewInfo.setFont(CyServiceModule.getService(IconManager.class).getIconFont(ICON_FONT_SIZE * 4 / 5));
        createViewInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createViewInfoMouseClicked(evt);
            }
        });

        dontCreateViewInfo.setFont(CyServiceModule.getService(IconManager.class).getIconFont(ICON_FONT_SIZE * 4 / 5)
        );
        dontCreateViewInfo.setText(ICON_QUESTION_CIRCLE_O);
        dontCreateViewInfo.setToolTipText(DONT_CREATE_VIEW_TIP);
        dontCreateViewInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dontCreateViewInfo.setMaximumSize(new java.awt.Dimension(32, 32));
        dontCreateViewInfo.setMinimumSize(new java.awt.Dimension(24, 24));
        dontCreateViewInfo.setPreferredSize(new java.awt.Dimension(24, 24));
        dontCreateViewInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dontCreateViewInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createViewRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dontCreateViewRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dontCreateViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createViewRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dontCreateViewRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dontCreateViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createViewInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createViewInfoMouseClicked
        JOptionPane.showMessageDialog(this,
        CREATE_VIEW_TIP, "Create View", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_createViewInfoMouseClicked

    private void dontCreateViewInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dontCreateViewInfoMouseClicked
       JOptionPane.showMessageDialog(this,
        DONT_CREATE_VIEW_TIP, "Don't Create View", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_dontCreateViewInfoMouseClicked

    private void createViewRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_createViewRadioButtonStateChanged
        validateOK();
    }//GEN-LAST:event_createViewRadioButtonStateChanged

    private void dontCreateViewRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dontCreateViewRadioButtonStateChanged
         validateOK();
    }//GEN-LAST:event_dontCreateViewRadioButtonStateChanged

    private void dontCreateViewRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontCreateViewRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dontCreateViewRadioButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		// TODO add your handling code here:
		setImportNetwork(true);
		setVisible(false);
	}// GEN-LAST:event_okButtonActionPerformed

	private void preferencesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_settingsButtonActionPerformed
		PreferencesDialog preferencesDialog = new PreferencesDialog(null, true);
		preferencesDialog.setLocationRelativeTo(this);
		preferencesDialog.setVisible(true);
		updateHeadingAndMessage();
	}// GEN-LAST:event_settingsButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed

		// TODO add your handling code here:
		setImportNetwork(false);
		setVisible(false);
	}// GEN-LAST:event_cancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LargeNetworkDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				NetworkSummary networkSummary = new NetworkSummary();
				networkSummary.setNodeCount(1000000);
				networkSummary.setEdgeCount(1000000);

				LargeNetworkDialog dialog = new LargeNetworkDialog(null, true, networkSummary);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel createViewInfo;
    private javax.swing.JRadioButton createViewRadioButton;
    private javax.swing.JLabel dontCreateViewInfo;
    private javax.swing.JRadioButton dontCreateViewRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup viewButtonGroup;
    // End of variables declaration//GEN-END:variables

	private boolean willCreateView() {
		final long networkSize = networkSummary.getNodeCount() + networkSummary.getEdgeCount();

		final long viewThreshold = CxPreferences.getViewThreshold();
		final CxPreferences.CreateViewEnum createViewPreference = CxPreferences.getCreateView();

		return createViewPreference.equals(CxPreferences.CreateViewEnum.ALWAYS) || networkSize < viewThreshold;
	}

	private boolean importNetwork = false;

	private void setImportNetwork(final boolean importNetwork) {
		this.importNetwork = importNetwork;
	}

	public boolean getImportNetwork() {
		return importNetwork;
	}
	
	public boolean getCreateView() {
		return createViewRadioButton.isSelected();
	}
}
