/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cytoscape.cyndex2.internal.ui.swing;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import org.cytoscape.cyndex2.internal.CyActivator;
import org.cytoscape.cyndex2.internal.util.ServerManager;
import org.cytoscape.cyndex2.internal.util.UserAgentUtil;
import org.ndexbio.model.object.NdexStatus;
import org.ndexbio.rest.client.NdexRestClient;
import org.ndexbio.rest.client.NdexRestClientModelAccessLayer;

/**
 *
 * @author dotasek
 */
public class SignInAdvancedDialog extends javax.swing.JDialog {

	final int ICON_FONT_SIZE = 44;
	
	
	private String serverURL = null;

	private boolean changed = false;

	public boolean isChanged() {
		return changed;
	}

	public String getNewServerURL() {
		return serverURL;
	}

	

	/**
	 * Creates new form NewJDialog
	 */
	public SignInAdvancedDialog(JDialog parent, final String serverURL) {
		super(parent, true);
		this.serverURL = serverURL;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverURLTextField = createServerURLField();
        serverURLLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        instructionText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NDEx Server Settings");
        setIconImage(null);

        serverURLTextField.setText(serverURL);
        serverURLTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverURLTextFieldActionPerformed(evt);
            }
        });

        serverURLLabel.setText("Server URL:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        instructionText.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        instructionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionText.setText("<html><body>Enter a valid NDEx server URL.</body></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serverURLLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverURLTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(instructionText, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(instructionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverURLLabel)
                    .addComponent(serverURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private JTextField createServerURLField() {
		JTextField serverURLTextField = new javax.swing.JTextField();
		serverURLTextField.setText(serverURL);
		serverURLTextField.getDocument().addDocumentListener(new DocumentListener() {
			public void changedUpdate(DocumentEvent e) {
				changed = true;
			}

			public void removeUpdate(DocumentEvent e) {
				changed = true;
			}

			public void insertUpdate(DocumentEvent e) {
				changed = true;
			}
		});
		return serverURLTextField;
	}

	private void serverURLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_uuidTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_uuidTextFieldActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		applySettings();
	}// GEN-LAST:event_okButtonActionPerformed

	private void cancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelActionPerformed
		changed = false;
		setVisible(false);
	}// GEN-LAST:event_cancelActionPerformed

	private void applySettings() {
		if (!changed || serverURLTextField.getText().trim().length() == 0) {
			System.out.println("Nothing changed. Leaving old server URL");
			setVisible(false);
			return;
		}

		System.out.println("Server URL changed. Verifying.");
		
		String verifiedURL;
		try {
			final String trimmedURL = serverURLTextField.getText().trim();
			final String baseRoute = ServerManager.getBaseRoute(trimmedURL);
			
			final NdexRestClient nc = new NdexRestClient(
					baseRoute);
			nc.setAdditionalUserAgent(UserAgentUtil.getUserAgent());
			final NdexRestClientModelAccessLayer mal = new NdexRestClientModelAccessLayer(nc);
			
			final NdexStatus status = mal.getServerStatus();
			verifiedURL = status.getProperties().size() > 0 ? trimmedURL : null;
			
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(this,
					"<html><body>Error validating NDEx Server URL: <br>" + e.getMessage() + "</html></body>", "Invalid URL",
					JOptionPane.WARNING_MESSAGE);
			verifiedURL = null;
		}

		if (verifiedURL != null) {
			
			serverURL = verifiedURL;
			setVisible(false);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SignInAdvancedDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SignInAdvancedDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SignInAdvancedDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SignInAdvancedDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {

				SignInAdvancedDialog dialog = new SignInAdvancedDialog(new javax.swing.JDialog(), "public.ndexbio.org");
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel instructionText;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel serverURLLabel;
    private javax.swing.JTextField serverURLTextField;
    // End of variables declaration//GEN-END:variables
}
